### Default Profile

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---

### JPA
spring:
  config:
    activate:
      on-profile: jdbc
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration

---

### JDBC
spring:
  config:
    activate:
      on-profile: jdbc
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.hazelcast.HazelcastJpaDependencyAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

---

### Debug Profile
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    show-sql: true
